### ISSUE TITLE
Docker compose YAML

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/docker-mdbook#1]
### Docker Compose

Create your `docker-compose.yml` like the following.

```yaml
version: '3'

services:
  mdbook:
    container_name: mdbook
    image: peaceiris/mdbook:v3.5.0
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname 0.0.0.0
```

### Usage

```sh
# Run "mdbook serve"
docker-compose up

# Run a command of mdBook
docker-compose run --rm mdbook test
```
